apiVersion: v1
kind: Namespace
metadata:
  name: rate-limiter
  labels:
    app.kubernetes.io/name: distributed-rate-limiter
    app.kubernetes.io/component: namespace
    environment: production
  annotations:
    description: "Namespace for distributed rate limiter service"
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: rate-limiter-quota
  namespace: rate-limiter
spec:
  hard:
    requests.cpu: "4"
    requests.memory: 8Gi
    limits.cpu: "8"
    limits.memory: 16Gi
    persistentvolumeclaims: "2"
    pods: "10"
    services: "5"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: rate-limiter-limits
  namespace: rate-limiter
spec:
  limits:
  - default:
      cpu: "1"
      memory: "1Gi"
    defaultRequest:
      cpu: "200m"
      memory: "512Mi"
    type: Container