apiVersion: v1
kind: ServiceAccount
metadata:
  name: rate-limiter
  namespace: rate-limiter
  labels:
    app.kubernetes.io/name: distributed-rate-limiter
    app.kubernetes.io/component: serviceaccount
automountServiceAccountToken: false
