apiVersion: v1
kind: ServiceAccount
metadata:
  name: rate-limiter
  namespace: rate-limiter
  labels:
    app.kubernetes.io/name: distributed-rate-limiter
    app.kubernetes.io/component: serviceaccount
automountServiceAccountToken: false
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: rate-limiter
  namespace: rate-limiter
  labels:
    app.kubernetes.io/name: distributed-rate-limiter
    app.kubernetes.io/component: rbac
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rate-limiter
  namespace: rate-limiter
  labels:
    app.kubernetes.io/name: distributed-rate-limiter
    app.kubernetes.io/component: rbac
subjects:
- kind: ServiceAccount
  name: rate-limiter
  namespace: rate-limiter
roleRef:
  kind: Role
  name: rate-limiter
  apiGroup: rbac.authorization.k8s.io