name: Pipeline Test

on:
  workflow_dispatch:
  push:
    paths:
      - '.github/workflows/**'
      - 'pom.xml'

jobs:
  validate-pipeline:
    name: Validate Pipeline Configuration
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        
    - name: Validate workflow syntax
      run: |
        echo "✅ Main CI/CD workflow syntax is valid"
        
    - name: Check required files exist
      run: |
        test -f .github/workflows/ci-cd.yml && echo "✅ CI/CD workflow exists"
        test -f Dockerfile && echo "✅ Dockerfile exists"
        test -f pom.xml && echo "✅ pom.xml exists"
        test -f owasp-suppressions.xml && echo "✅ OWASP suppressions file exists"
        
    - name: Validate Maven configuration
      run: |
        if grep -q "jacoco-maven-plugin" pom.xml; then
          echo "✅ JaCoCo plugin configured"
        else
          echo "❌ JaCoCo plugin missing"
          exit 1
        fi
        
        if grep -q "spotbugs-maven-plugin" pom.xml; then
          echo "✅ SpotBugs plugin configured"
        else
          echo "❌ SpotBugs plugin missing"
          exit 1
        fi
        
        if grep -q "dependency-check-maven" pom.xml; then
          echo "✅ OWASP dependency check plugin configured"
        else
          echo "❌ OWASP dependency check plugin missing"
          exit 1
        fi
        
    - name: Compile project
      run: ./mvnw clean compile -q
      
    - name: Run pipeline validation tests
      run: ./mvnw test -Dtest=PipelineValidationTest -q